apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: three-tier
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: Admin@12345
  MONGO_CONN_STR: mongodb://admin:Admin%4012345@mongodb:27017/three-tier?authSource=admin
